---
functional:
  - Сайт должен работать на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Должна быть форма регистрации
  - Должна быть возможность создания игр различного уровня сложности
  - Должна быть возможность создания игр на разных языках программирования
  - Должна быть возможность создания игр с ботом, случайным игроком и выбором соперника
  - Должна быть страница рейтинга игроков
  - За победные игры должны быть бонусы игрокам
  - Должна быть возможность обмена сообщениями между игроками
